import 'package:quote_app/model/quote_model.dart';

List quote= [
Question.name("You have power over your mind — not outside events. Realize this, and you will find strength.", "Marcus Aurelius"),
Question.name("Divide each difficulty into as many parts as is feasible and necessary to resolve it.", "René Descartes"),
Question.name("Be weird. Your strangeness is your magic.", "Parker Lewis"),
Question.name("What you seek is seeking you.", "Rumi"),
Question.name("If you have everything under control, you’re not moving fast enough.", "Mario Andretti"),
Question.name("One small positive thought can change your whole day.", "Unknown"),
Question.name("To escape criticism: do nothing, say nothing, be nothing.", "Elbert Hubbard"),
Question.name("What makes you different or weird—that’s your strength.", "Meryl Streep"),
Question.name("Your greatest dreams are all on the other side of the wall of fear and caution.", "Unknown"),
Question.name("Know your limits but never stop trying to exceed them.", "Unknown"),
Question.name("Stop managing your time. Start managing your focus.", "Robin Sharma"),
Question.name("The difference between ordinary and extraordinary is that little extra.", "Jimmy Johnson"),
Question.name("Peace in the world is everybody's business, no matter where you live or what you do.", "Betty Williams"),
Question.name("Balance is not something you find, it's something you create.", "Jana Kingsford"),
Question.name("Perfection is not attainable, but if we chase perfection, we can catch excellence.", "Vince Lombardi"),
Question.name("Always do your best. What you plant now, you will harvest later.", "Og Mandino"),
Question.name("People overestimate what they can do in a single day. And underestimate what they can do in their whole lives.", "Unknown"),
Question.name("Everything is difficult until you know how to do it.", "Anonymous"),
Question.name("Adopt the pace of nature, her secret is patience.", "Ralph Emerson"),
Question.name("Believe in your infinite potential. Your only limitations are those you set upon yourself.", "Roy T. Bennett"),
Question.name("Let your hopes, not your hurts, shape your future.", "Robert H. Schuller"),
Question.name("Perseverance is not a long race; it is many short races one after another.", "Walter Elliott"),
Question.name("Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.", "John Quincy Adams"),
Question.name("Yesterday, you said tomorrow.", "Nike"),
Question.name("Do what you feel in your heart to be right. You’ll be criticized anyway.", "Eleanor Roosevelt"),
Question.name("Be curious about everything. Never stop learning. Never stop growing.", "Caley Alyssa"),
Question.name("Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", "Thomas A. Edison"),
Question.name("Acknowledging the good that you already have in your life is the foundation for all abundance.", "Eckhart Tolle"),
Question.name("If people aren't laughing at your dreams, your dreams aren't big enough.", "Grayson Marshall"),
Question.name("Be careful how you are talking to yourself because you are listening.", "Lisa M. Hayes"),
Question.name("There are two primary choices in life: to accept conditions as they exist, or accept the responsibility for changing them.", "Denis Waitley"),
Question.name("You cannot protect yourself from sadness without protecting yourself from happiness.", "Jonathan Safran Foer"),
Question.name("You cannot change the circumstances but you can change yourself. That is something you have charge of.", "Jim Rohn"),
Question.name("Today is the most important day of our lives.", "Thich Nhat Hanh"),
Question.name("Nothing is impossible, the word itself says 'I'm possible'!", "Audrey Hepburn"),
Question.name("Inside of every problem lies an opportunity.", "Robert Kiyosaki"),
Question.name("Do what you dream of doing even while you're afraid.", "Arianna Huffington"),
Question.name("Worrying does not take away tomorrow's troubles, it takes away today's peace.", "Unknown"),
Question.name("The universe reveals its secrets to those who dare to follow their hearts.", "Ralph Smart"),
Question.name("A positive attitude causes a chain reaction of positive thoughts, events, and outcomes.", "Wade Boggs"),
Question.name("Life is a series of building, testing, changing and iterating.", "Lauren Mosenthal"),
Question.name("May your choices reflect your hopes, not your fears.", "Nelson Mandela"),
Question.name("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
Question.name("To accomplish great things, we must not only act, but also dream, not only plan, but also believe.", "Anatole France"),
Question.name("Don't let the success of others discourage you. Let it inspire you.", "Unknown"),
Question.name("Never give up. Never let things out of your control dictate who you are.", "Unknown"),
Question.name("Any person capable of angering you becomes your master. They can anger you only when you permit yourself to be disturbed by them.", "Epictetus"),
Question.name("Let us make our future now, and let us make our dreams tomorrow's reality.", "Malala Yousafzai"),
Question.name("If you listen to your fears, you will die never knowing what a great person you might have been.", "Robert Schuller"),
Question.name("Every day of our lives, we are on the verge of making those slight changes that would make all the difference.", "Mignon McLaughlin"),
Question.name("Never look back unless you are planning to go that way.", "Henry David Thoreau"),
Question.name("By doing what you love you inspire and awaken the hearts of others.", "Satsuki Shibuya"),

 

];

